#ifndef SINGULARITY_ENGINE_RENDERER
#define SINGULARITY_ENGINE_RENDERER
#include "Common.h"
#include "rendererAPI/IShader.h"
#include "RendererAPI/IPipeline.h"
#include "RendererAPI/IIndexBuffer.h"
#include "RendererAPI/IVertexBuffer.h"
#include "RendererAPI/VertexTypes.h"
#include "RendererAPI/renderer.h"
#include "vulkan/Pipeline/VulkanPipeline.h"
#endif // 