#ifndef SINGULARITY_ENGINE_RENDERER
#define SINGULARITY_ENGINE_RENDERER
#include "Common.h"
#include "rendererAPI/IShader.h"
#include "RendererAPI/IPipeline.h"
#include "RendererAPI/IBuffer.h"
#include "RendererAPI/VertexTypes.h"
#include "RendererAPI/renderer.h"
#endif // 